markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Sukhwinder Lall
production_url : http://carlosbecker.com
description: "Sukhwinder Lall."
disqus_shortname: lallsonu
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Sukhwinder Lall
  github : lallsonu
  twitter : lall_sonu
  email: lallsonu1992@gmail.com
